apiVersion: v1
kind: Deployment
metadata:
  name: deploybot-deployment
  labels:
    app: deploybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploybot-containers
  template:
    metadata:
      labels:
        app: deploybot-containers
    spec:
      containers:
      - name: web
        image: nwochaadim/deploybot:latest
        ports:
        - containerPort: 1323
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: bot-credentials
                key: aws_access_key_id

          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: bot-credentials
                key: aws_secret_access_key

          - name: CLOUDFORMATION_URL
            valueFrom:
              secretKeyRef:
                name: bot-credentials
                key: cloudformation_url

          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: bot-credentials
                key: github_token

          - name: GITHUB_USERNAME
            valueFrom:
              secretKeyRef:
                name: bot-credentials
                key: github_username

          - name: GOBBLE_CLOUDFORMATION_DIR
            valueFrom:
              secretKeyRef:
                name: bot-credentials
                key: gobble_cloudformation_dir

          - name: GOBBLE_DIR
            valueFrom:
              secretKeyRef:
                name: bot-credentials
                key: gobble_dir

          - name: GOBBLE_URL
            valueFrom:
              secretKeyRef:
                name: bot-credentials
                key: gobble_url

          - name: GO_ENV
            valueFrom:
              secretKeyRef:
                name: bot-credentials
                key: go_env

          - name: POST_URL
            valueFrom:
              secretKeyRef:
                name: bot-credentials
                key: post_url

          - name: SLACK_SIGNING_SECRET
            valueFrom:
              secretKeyRef:
                name: bot-credentials
                key: slack_signing_secret

          - name: SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: bot-credentials
                key: slack_token

          - name: REDIS_URL
            value: deploybot-service:6379
