apiVersion: v1
kind: Service
metadata:
  name: deploybot-service
spec:
  selector:
    app: deploybot-containers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1323
  type: LoadBalancer
